extends:
  - './node_modules/lint-rules/eslint/index.js'
rules:
  comma-dangle:
  - error
  - arrays: always-multiline
    objects: always-multiline
    imports: always-multiline
    exports: always-multiline
    functions: always-multiline